DATASET:
  name: 'HCOCO'
  root_dataset: "/storage/jevnisek/ImageHarmonizationDataset/"
  list_train: "./data/HCOCO-training.odgt"
  list_val: "./data/HCOCO-validation.odgt"
  num_class: 2


MODEL:
  arch: "Deeplabv3"
  encoder_name: "resnet34"

TRAIN:
  batch_size_per_gpu: 8
  num_epochs: 25
  optim: "Adam"
  lr: 1e-4


VAL:
  visualize: False
  checkpoint: "epoch_25.pth"

TEST:
  checkpoint: "epoch_25.pth"
  result: "./"

DIR: "/storage/jevnisek/ImageHarmonizationResults/ckpt/HCOCO-Deeplabv3-resnet34"
